<?php

namespace BYD\CoreBundle\Repository;

/**
 * ContactMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
