# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    byd.form.registration:
        class: BYD\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: byd_user_registration }